name: 'Angular test workflow'
on:
  push:
    branches:
      - 'main'
      - 'feat/**'
      - 'fix/**'
      - 'chore/**'
      - 'release/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: check repo
      uses: actions/checkout@v3

    - name: Use Node.js 18.13.0
      uses: actions/setup-node@v1
      with:
        node-version: 18.13.0
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build
      #run: npm run build -- --prod
      run: npm run build
    - name: Test
      #run: npm test -- --configuration=ci
      run: npm test -- --code-coverage
    #- name: E2E
    #  run: npm run e2e -- --configuration=ci
